---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Z_End.
--- DateTime: 2025/3/13 00:38
---

---@class CardActionBridge
---@field ToTick fun(self:CardActionBridge)
---@field DontClosePopup boolean
---

---@class int

---@class CardData
---@field BlueprintUnlockSunsCost number
---@field BuildingDaytimeCost int
---@field DeconstructDaytimeCost int
---

---@class DurabilityStat
---

---@class CardTag
---
