---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Z_End.
--- DateTime: 2025/3/11 23:34
---

---@class CountedCard
---@field Card UniqueIdObjectBridge
---@field Count number
CountedCard = {}

---@param idOrName string
---@param count number
function CountedCard.new(idOrName, count)
    local ins = { Card = Game:GetItem(idOrName), Count = count }
    return ins
end

---@class BpStageEle:CountedCard
---@field Spend boolean
---@field UsageCost number
BpStageEle = {}

function BpStageEle.new(idOrName, cost, spend)
    ---@type BpStageEle
    local ins = CountedCard.new(idOrName, (spend and 1) or cost)
    ins.Spend = spend
    ins.UsageCost = cost
    return ins
end

